---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rhoso2

resources:
  - netconfig.yaml
  - openstackcontrolplane.yaml
  - endpoint-cleanup-job.yaml

labels:
  - pairs:
      deployment: no-cinder
      gitops: argocd
