---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rhoso1

resources:
  - ../../base

# You can add patches here if needed for environment-specific customizations
# patches:
#   - target:
#       kind: OpenStackControlPlane
#       name: openstack-galera
#     patch: |-
#       - op: replace
#         path: /spec/nova/template/apiServiceTemplate/replicas
#         value: 3
