---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - netconfig.yaml
  - openstackcontrolplane.yaml

labels:
  - pairs:
      deployment: nvidia-l4-passthrough
      gitops: argocd
